---
title: "Academic"
---

[Academic CV](pdfs/cv-academic-Rohan_Alexander.pdf)  

# Published papers
* Rohan Alexander and Zach Ward, 2018, '[Age at Arrival and Assimilation During the Age of Mass Migration](https://www.cambridge.org/core/journals/journal-of-economic-history/article/age-at-arrival-and-assimilation-during-the-age-of-mass-migration/85FDB674232C30BDD889711D343F22FE)', *The Journal of Economic History*, 78(3), 904-937.  
[Working paper version](pdfs/2018_02_21-Age_at_arrival.pdf).


# Working papers
* [Monica Alexander](monicaalexander.com) and Rohan Alexander, '[The Effect of Elections and Prime Ministers on Discussion in the Australian Federal Parliament (1901—2018)](pdfs/AlexanderAlexander-EffectofElectionsandPrimeMinisters.pdf)'.  
* Rohan Alexander and Tim Hatton, 'The Making of a Nation: Who Voted for Australian Federation?'.
* Rohan Alexander and Patrick Leslie, 'The Effect of State on Senators’ Speeches in the Australian Federal Parliament (1901–2018)'
* Rohan Alexander, Patrick Dumond, Lauren Kennedy, and Patrick Leslie, ‘Forecasting Parliamentary Elections’.


# Datasets

* `AustralianPoliticians` is an R package that consists of a collection of datasets related to Australian politicians. The datasets are up-to-date as of 30 November 2019. You can install the package from [GitHub](https://github.com/RohanAlexander/AustralianPoliticians).
* `AustralianElections` is an R package that consists of a collection of datasets related to Australian elections. The datasets are up-to-date as of 10 September 2019. You can install the package from [GitHub](https://github.com/RohanAlexander/AustralianElections).



# Presentations
* Forecasting Parliamentary Elections  
    10 December 2019, Monash University, Department of Econometrics & Business Statistics, Melbourne.  
    9 December 2019, Australian Society for Quantitative Political Science Conference, Melbourne.  
    2 December 2019, Australian National University, Cake for Comments, Canberra.  
    20 November 2019, POP Politics Workshop, Canberra.  
    17 October 2018, University of Toronto, Political Behaviour Group, Toronto.  
* A Word-Count Based Classifier of Politicians in the Australian Federal Parliament (1901--2018)  
    4 September 2019, European Consortium for Political Research, General Conference, Wroclaw.  
    22 June 2019, European Political Science Association, Annual Conference, Belfast.  
    18 June 2019, Quantitative Text Analysis Workshop, Dublin.
*  The Effect of Elections and Prime Ministers on Discussion in the Australian Federal Parliament (1901—2018)  
    11 January 2019, Political Methodology Specialist Group, Annual Conference, Warwick.  
    11 December 2018, Max Planck Institute for Demographic Research, Rostock.  
    22 November 2018, University of Toronto, Political Behaviour Group, Toronto.  
    25 October 2018, Australian National University, Research School of Economics, Canberra.  
    25 October 2018, Parliamentary Library, Parliament of Australia, Canberra.  
    24 October 2018, Australian National University, School of Politics and International Relations, Canberra. 
* Exploring Australia's Hansard (1901--2017)  
    (Poster) 7-9 September, 2018 Economic History Association Meeting, Montreal.
* A Surnames-Based Analysis of Tasmanian Social Mobility (1803--2015)  
    20 May 2016, UC Berkeley, Economic History Lunch, Berkeley.  
    2 May 2016, Australian National University, Research School of Economics, Canberra.

