---
title: "Other"
description: |
  Contains my bookshelf, my book recommendations, a little bit about my professional experience, and some fun projects.
---

# Bookshelf

* -"A Little Life", Hanya Yanighara. Recommended by Lauren.
* "The Andromeda Strain", Michael Crichton.
* "Is There Life After Housework", Don Aslett.  
Got given this at the Museum of Clean in Pocatello, Idaho. The museum was surprisingly good!
* "The Chosen", Chaim Potok.
* "The Forsyth Saga", John Galsworthy.
* "Freakonomics", Steven Levitt and Stephen Dubner.
* "Tess of the D'Urbervilles", Thomas Hardy.
* "King Charles III", Anthony Holden.
* "The Road Washes Out in Spring", Baron Wormser.  
Stayed at the author's house, so bought some of his books and particularly liked this one about how his family lived off the grid in New England. Liked it even better after living in Amherst for a while.
* "The Shepherd's Hut", Tim Winton.  
Present from Helen.
* **"Code: The Hidden Language of Computer Hardware and Software", Charles Petzold.**
* "Hitch-22", Christopher Hitchens.
* "Audacity of Hope", Barack Obama.
* "Kennedy", Ted Sorenson.
* "The Son Also Rises", Greg Clark.
* "My Life", Bill Clinton.
* "The Art of the Deal", Donald Trump and Tony Schwartz. This book is terrible. Read that [NYT article](https://www.nytimes.com/interactive/2018/10/02/us/politics/donald-trump-tax-schemes-fred-trump.html) about how he really made his money instead.
* "Life, on the Line", Grant Achatz and Nick Kokonas.
* "The Pelican Brief", John Grisham.
* "Cameron", Francis Elliot and James Hanning. I haven't yet come across a good David Cameron biography, but this one was interesting. Focused on pre-parliament period.
* "Lightning Rods", Helen DeWitt.
* "All Too Human", George Stephanopoulos. I thought that politics was romantic until I read this book when I was 20.
* "Hansons Half-Marathon Method", Luke Humphrey.
* **"The Remains of the Day", Kazuo Ishiguro.**
* **"An Equal Music", Vikram Seth.**
* -"Zero to One", Peter Thiel. Maybe it's the jet-lag, but is this a business book that's actually not terrible? A few weak chapters, but enough interesting ones to outweigh them.
* "Harry Potter", J. K. Rowling.
* "The Book of Basketball", Bill Simmons.
* "The Crime of the Century", Kingsley Amis.
* **-"Bad Blood: Secrets and Lies in a Silicon Valley Startup", John Carreyrou.** About Theranos, a company that faked blood test results.
* "Hansons Marathon Method", Luke Humphrey. Bought this; followed this; ran my best marathon.
* "Moneyball", Michael Lewis.
* -"Devil's Bargain", Joshua Green. About Bannon and his relationship with Trump. Worthwhile reading in and of itself, but the interaction with 'Chasing Hillary' was especially good. Neither is quantitative, but both help to understand 2016 e.g. how could the Comey reopening have a statistical effect? Green shows Bannon spent years creating specific mainstream doubts re Clinton. Chozick shows how/why Clinton campaign decisions accentuated them. I'm as keen on quant political analysis as anyone (shout out to @petitpoll if you want Australian polling!), but the snippets (and there was not much unfortunately) about each campaign's quant groups made me wonder if we have a cohort issue ATM. Specifically, do those in charge of political campaigns (or for that matter many businesses) know enough quant to know it's important, but not enough to appreciate, and hence be able to compensate for, it's weaknesses?
* "The Girl Who Kicked The Hornet's Nest", Stieg Larsson.
* "Island Home", Tim Winton.
* "One Bullet Away", Nathaniel Fick.
* "The Tenth Man", Graham Green.
* "The Sound of One Hand Clapping", Richard Flanagan. Present from Helen.
* "Berkeley Walks", Robert E Johnson and Janet L Byron.
* "Some Trick", Helen DeWitt.
* "Why Australia Prospered", Ian McLean.
* **"R for Data Science", Garrett Grolemund and Hadley Wickham.** Some people convert to Catholicism when they get married, I converted to R. But my knowledge was piecemeal and going through this book addressed that.
* "Middlesex", Jeffrey Eugenides.
* **"The Last Samurai", Helen DeWitt.** Nothing to do with the Tom Cruise movie.
* "The Unconsoled", Kazuo Ishiguro.
* "The English Patient", Michael Ondaatje.
* "The Zhivago Affair", Peter Finn and Petra Couvée. Present from Bec.
* "The Buried Giant", Kazuo Ishiguro.
* "The Princess Casamassima", Henry James.
* "Swan Song", John Galsworthy.
* **"The Golden Gate", Vikram Seth.**
* "Dilbert", Scott Adams.
* "A Thousand Days", Arthur Schlesinger.
* "Gone Girl", Gillian Flynn.
* "Manufacturing Consent", Edward Herman and Noam Chomsky.
* **"The Making of the Atomic Bomb", Richard Rhodes.** Covers the physical, social, and political factors that culminated in the US dropping atomic bombs on Japan at the end of World War II.
* "The Moor's Last Sigh", Salman Rushdie.
* "Blood Year", David Kilcullen.
* "Vanity Fair", William Thackeray.
* "The Canterbury Tales", Geoffrey Chaucer.
* "The Poetry Life: Ten Stories", Baron Wormser.
* "Vineland", Thomas Pynchon.
* "Fables", Aesop.
* "Runner's World The Runner's Body", Ross Tucker and Jonathan Dugas.
* "Decoded", Jay Z.
* "A Perfect Spy", John le Carré. Dad likes le Carré so I buy them when there's a nice edition.
* "What a Croc: Legendary Front Pages From the NT News". Present from Mark.
* "The Summons", John Grisham.
* "Seven Pillars of Wisdom",  TE Lawrence. 'Borrowed' from Dad.
* "Cloudstreet", Tim Winton. All Australians have a copy of this. I think it's in the law or something.
* "The Noma Guide to Fermentation", Rene Redzepi and David Zilber.
* "Alice Waters and Chez Panisse", Thomas McNamee.
* "The Junior Officers' Reading Club", Patrick Hennessey.
* "Rumpole", John Mortimer.
* **-"The Dream Machine", M. Mitchell Waldrop.**
* "The Loved One", Evelyn Waugh.
* **"The Challenger Launch Decision", Diane Vaughan.** One of the greatest non-fiction books ever.
* "Purity", Jonathan Franzen. Bought this while I was in Oakland, mostly because the main character lived in Oakland.
* "The Information", Martin Amis.
* **-"Hard Landing", Thomas Petzinger.** About the deregulation of the US airline market.
* **"The Best and the Brightest", David Halberstam.** I read Plato's Republic at an impressionable age and so I used to think that if we could just put the smart people in charge then the 'right' decisions would be made. This book cured me of that.
* "Our Game", John le Carré.
* "Margaret Thatcher", Charles Moore. Present from Dad
* "The Rosie Project", Graeme Simson.
* "End of the Chapter", John Galsworthy.
* "Data Analysis Using Regression and Multilevel Hierarchical Models", Andrew Gelman and Jennifer Hill. Ah, the money-maker! Thank you Gelman and Hill. I haven't properly studied this book, just dipped in and out as needed, but Monica's probably read it more than enough for both of us.
* "Middlemarch", George Eliot.
* "War and Peace", Leo Tolstoy.
* **"Open", Andre Agassi.** Tennis is incidental to the aspects that make this book great, so try it even if you don't particularly like the sport. I can't remember who recommended it -- seems like a Nick Crocker type of book?
* "Introduction to Statistical Learning", Daniela Witten, Gareth James, Robert Tibshirani, and Trevor Hastie. Going through this with Peter taught me a lot including: 1) if you want to learn something then buy a physical copy of a textbook, get a partner and commit to weekly chapter reviews; 2) learn statistics from statisticians; and 3) statistics is awesome and I want to learn more. I always thought that I was terrible at it because econometrics never came easily to me, but now I realise that maybe the econometrics-approach isn't for me, but the statistics one is.
* "A Thousand Days", Arthur Schlesinger.
* -**"The Pixar Touch", David A. Price.** Incredible details about their overnight success, 23 years in the making.
* "Stop At Nothing", Annabel Crabb.
* -**"Fire and Ashes: Success and Failure in Politics", Michael Ignatieff.** Changed the way that I thought about politics.
* "Political Animal", David Marr.
* "Triumph and Demise", Paul Kelly. Present from Dad.
* **"Skyfaring", Mark Vanhoenacker.** Read this on your next flight.
* **"A Suitable Boy", Vikram Seth.**
* -"Chasing Hillary", Amy Chozick. Extended 2016 Clinton campaign diary. Many (most?) campaign dairies are terrible but this is worthwhile reading in and of itself and the interaction with 'Devil's Bargain' was especially good. See notes for 'Devil's Bargain'.
* "Stress Test", Timothy Geithner.
* "Elements of Statistical Learning", Jerome H. Friedman, Robert Tibshirani, and Trevor Hastie.
* "Officers and Gentlemen", Evelyn Waugh.


# Best books that I read in:

* 2019
    - Hahahahaha, the baby was born in 2019.
* 2018: 
    - "Bad Blood" John Carreyrou; 
    - "Devil's Bargain" Joshua Green & "Chasing Hillary" Amy Chozick; 
    - "Hard Landing" Thomas Petzinger; 
    - "Open" Andre Agassi; 
    - "Some Trick" Helen DeWitt; 
    - "The Dream Machine" M Mitchell Waldrop; and 
    - "The Pixar Touch" David A Price.



# Professional experience

<!-- [Professional CV](pdfs/cv-professional-RohanAlexander.pdf) -->

### Grosvenor Public Sector Advisory

Consultant,   April 2017 -- February 2019

I consulted at Grosvenor on a casual basis to complete a specific project for the European Commission relating to public procurement. This involved: identifying data sources; preparing for and supporting data acquisition; conducting data quality confirmation; helping with survey design and validation; and some minor managerial responsibilities.


### The Centre for International Economics

Economist, January 2012 -- August 2013; August 2015 -- November 2015

The CIE is a privately-owned economic consultancy. I contributed to reports for public- and private-sector clients as part of a small team. Topics included: valuing public sector outputs; housing sector taxation; the global meat market; wheat price elasticities; variations to modern awards; migration; and labor markets.


### GoCampaign

Co-founder and Director, July 2011 -- May 2015

As a co-founder and director of GoCampaign (later GoCatalyze), a data analysis tool, I was responsible for the creation and development of a business along with Andrew Barnes, Chris Eigeland and Chris Hood. There were many aspects to this including creating marketing material and websites; making pitch decks; customer on-boarding and service; presenting; market testing; and some minor managerial responsibilities. GoCatalyze completed the ANZ Innovyz START accelerator program in 2013 and won the iAward Data Category in 2014. GoCatalyze is now part of GO1. 


### Reserve Bank of Australia

Cadet/Analyst/Senior Analyst, February 2009 -- December 2011

I researched topics related to banknotes, for example an econometric analysis of banknote demand during the 2007-08 financial crisis. I was also responsible for creating and analysing counterfeit banknote datasets, and gave banknote-related presentations to the public.




# Projects

### Petit Poll

May 2016 -- *Current*

This is a joint project with [Monica Alexander](https://www.monicaalexander.com). Petit Poll combines non-representative polling data with a hierarchical Bayesian model to cheaply deliver meaningful Australian political polling. I am responsible for survey design and analysis, as well as marketing and communication.

We polled the 2016 Australian Federal election and got a (statistically) reasonable result. In terms of seats we were five off. Four of those were just a result of our small sample size: there were the three that turned unexpectedly in Tasmania; and the one in South Australia that went to the Nick Xenophon team. If we had more data from those areas then the model would have had a better chance, but when there’s not much data the prior has a big impact.

### No Pour Choices 

July 2018 -- *Current*

This is a a joint project with Adam Jansen and Ben Readshaw. No Pour Choices is an app that helps organise your wine collection. I am responsible for all aspects of iOS development.

