---
title: "Toronto Data Workshop"
description: |
---

**We thank Wendy Duff and the Faculty of Information; and Radu Craiu and the Department of Statistical Sciences for their support of these stipends.**

# Call for stipend applications

*15 June 2020*

Kelly Lyons and Rohan Alexander are announcing three research stipends, each of $1,000, for University of Toronto students or recent graduates who are from a group that is under-represented in STEM. This could include racial, gender, or other minorities. The successful applicants will be invited to prepare a research paper on a topic of their choice under the supervision of a faculty mentor, and will be given the opportunity to present their paper at a meeting of the Toronto Data Workshop.

If you are interested in applying for this opportunity please email [rohan.alexander@utoronto.ca](mailto:rohan.alexander@utoronto.ca), by the end of Monday 29 June 2020, attaching a single PDF that contains:

1) a brief (1 page) overview of what your paper will be about (some aspect of this paper should involve real-world data);
2) your CV; and
3) the name of a faculty member who has agreed to supervise this work.

If you do not have a faculty supervisor already, then any of the following current or future faculty are happy to supervise, and you should get in touch with one that matches your interests:

- [Kelly Lyons](http://individual.utoronto.ca/klyons/) (Information)
- [Monica Alexander](https://www.monicaalexander.com/) (Statistics and Sociology)
- [Rohan Alexander](https://rohanalexander.com/) (Information and Statistics)
- [Vianey Leos Barajas](https://vleosbarajas.com/) (Statistics and Environment)

If you have any questions about your application, then please email [rohan.alexander@utoronto.ca](mailto:rohan.alexander@utoronto.ca) before the closing date.



