---
title: "Teaching"
description: |
  My teaching is informed not only by my time in academia, but also by my experience working at my own start-up and in government. My approach is best characterised as practical, research-based, and emphasising workflow. I am an [RStudio Certified Tidyverse Trainer](https://education.rstudio.com/trainers) and I enjoy teaching students from a wide range of backgrounds. In general, I aim to help students learn how to tell stories with data. I have put together some notes to support my teaching, and these are available here: https://www.tellingstorieswithdata.com/.
---

# University of Toronto
* *(Upcoming)* Instructor, 'INF2178: Experimental Design for Data Science', Faculty of Information, Winter 2021
* *(Upcoming)* Instructor, 'STA304: Surveys, Sampling and Observational Data', Department of Statistical Sciences, Fall 2020
* Instructor, 'INF2178: Experimental Design for Data Science', Faculty of Information, Winter 2020, [evaluations](pdfs/2020-06-15-2020-INF2178.pdf)


# Australian National University
* Tutor, Macroeconomics 3, Semester 2, 2017, [evaluations](pdfs/2018-02-05-Sem_2_2017-ECON3102_-_Macroeconomics_3.pdf) 
* Tutor, Microeconomics 3, Semester 1, 2017, [evaluations](pdfs/2018-02-05-Sem_1_2017-ECON3101_-_Microeconomics_3.pdf) 
* Tutor, Behavioural Economics, Semester 2, 2015, [evaluations](pdfs/2018-02-05-Sem_2_2015-ECON2013_Behavioural_Economics.pdf) 
* Tutor, Business Economics, Semester 1, 2015, [evaluations](pdfs/2018-02-05-Sem_1_2015-ECON8069_Business_Economics.pdf) 
* Tutor, Microeconomics 1, Semester 1, 2013, [evaluations](pdfs/2018-02-05-Sem_1_2013-ECON1101_Microeconomics_1.pdf) 
* Tutor, Foundations of Economic and Financial Models, Semester 2, 2012

# University of Queensland
* Tutor, Microeconomic Policy, Semester 2, 2008
* Tutor, Microeconomic Theory, Semester 1, 2008
* Tutor, Introductory Microeconomics, Semester 2, 2007
* Tutor, Introductory Microeconomics, Semester 1, 2007


# Short courses and workshops
* Instructor, Gathering Data from Messy Sources
    - University of Toronto, Independent Summer Statistics Community, 22 May 2020.

* Instructor, [Getting started with MRP](http://rohanalexander.com/posts/2019-12-04-getting_started_with_mrp/)
    - Australian National University, 3 December 2019.
    
* Instructor, Introduction to Blogdown
    - Australian National University, RSE, 21 July 2017.

* Instructor, Introduction to LaTeX
    - Australian National University, RSE, 13 September 2017.
    - Australian National University, RSE, 3 May 2016.
